config/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'portfolio'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'portfolio'

urlpatterns = [
    path('', views.home_page_view),
    path('home', views.home_page_view, name='home'),
    path('aboutme', views.aboutme_page_view, name='aboutme'),
    path('projects', views.projects_page_view, name='projects'),
    path('blog', views.blog_page_view, name='blog'),
    path('quizz', views.quizz_page_view, name='quizz'),
    path('contact', views.contact_page_view, name='contact'),
    path('novacadeira', views.novacadeira_page_view, name='novacadeira'),
    path('novoprojeto', views.novoprojeto_page_view, name='novoprojeto'),
    path('novotfc', views.novotfc_page_view, name='novotfc'),
    path('login', views.login_page_view, name='login'),
    path('logout', views.logout_page_view, name='logout'),
    path('web', views.web_page_view, name='web'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/models.py
from django.db import models


# Create your models here.


class Post(models.Model):
    titulo = models.CharField(max_length=50)
    descricao = models.TextField()
    autor = models.CharField(max_length=100)
    criado = models.DateTimeField(auto_now_add=True)
    link = models.URLField(blank=True)

    def __str__(self):
        return self.titulo[:50]


class PontuacaoQuizz(models.Model):
    nome = models.CharField(max_length=100)
    pontuacao = models.IntegerField()

    def __str__(self):
        return self.nome[:50]


# DER

class ProfessorTeorica(models.Model):
    nome = models.CharField(max_length=50, primary_key=True)
    linkLusofona = models.URLField(blank=True)
    linkLinkedin = models.URLField(blank=True)

    def __str__(self):
        return self.nome[:50]


class ProfessorPratica(models.Model):
    nome = models.CharField(max_length=50, primary_key=True)
    linkLusofona = models.URLField(blank=True)
    linkLinkedin = models.URLField(blank=True)

    def __str__(self):
        return self.nome[:50]


class Cadeira(models.Model):
    nome = models.CharField(max_length=50, primary_key=True)
    ranking = models.IntegerField()
    ano = models.IntegerField()
    topicos = models.TextField()
    etcs = models.IntegerField()
    docente_teorica = models.ForeignKey(ProfessorTeorica, on_delete=models.CASCADE, default="")
    docente_pratica = models.ForeignKey(ProfessorPratica, on_delete=models.CASCADE, default="")

    def __str__(self):
        return self.nome[:50]


class Projeto(models.Model):
    nome = models.CharField(max_length=50, primary_key=True)
    cadeira = models.ManyToManyField(Cadeira, related_name='tem')
    imagem = models.ImageField(upload_to='static/portfolio/images')
    descricao = models.TextField()

    def __str__(self):
        return self.nome[:50]


class TFC(models.Model):
    titulo = models.CharField(max_length=50, primary_key=True)
    autor1 = models.CharField(max_length=50)
    autor2 = models.CharField(max_length=50)
    orientador = models.CharField(max_length=50)
    ano = models.IntegerField()
    resumo = models.TextField()
    link = models.URLField(blank=True)
    imagem = models.ImageField(upload_to='static/portfolio/images')

    def __str__(self):
        return self.titulo[:50]


class Tecnologia(models.Model):
    nome = models.CharField(max_length=50, primary_key=True)
    criador = models.CharField(max_length=50)
    dataLancamento = models.CharField(max_length=50)
    descricao = models.TextField()
    link = models.URLField(blank=True)
    imagem = models.ImageField()

    def __str__(self):
        return self.nome[:50]

portfolio/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post, Cadeira, Projeto, TFC


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        # inserção de classes CSS para formatação de cada campo do formulário
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'insert title...'}),
            'descricao': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'insert text...'}),
            'link': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g http...'}),
            'autor': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g John...'}),

        }

        # texto a exibir junto à janela de inserção
        labels = {
            'titulo': 'Title',
            'descricao': 'Description',
            'link': 'Link',
            'autor': 'Autor',
        }

        # texto auxiliar a um determinado campo do formulário
        help_texts = {
            'link': '*optional',
        }


class CadeiraForm(ModelForm):
    class Meta:
        model = Cadeira
        fields = '__all__'


class ProjetoForm(ModelForm):
    class Meta:
        model = Projeto
        fields = '__all__'


class TFCForm(ModelForm):
    class Meta:
        model = TFC
        fields = '__all__'

portfolio/views.py
import base64
import io
import urllib

import matplotlib
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

import urllib
from urllib.parse import urlparse

import datetime

from portfolio.forms import PostForm, CadeiraForm, ProjetoForm, TFCForm
from portfolio.models import *

from matplotlib import pyplot as plt

matplotlib.use('Agg')


def home_page_view(request):
    agora = datetime.datetime.now()

    context = {
        'hora': agora.hour,
    }

    return render(request, 'portfolio/home.html', context)


def login_page_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(
            request,
            username=username,
            password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('portfolio:home'))
        else:
            return render(request, 'portfolio/aboutme.html', {
                'message': 'Credenciais Inválidas'
            })
    return render(request, 'portfolio/login.html')


def logout_page_view(request):
    logout(request)

    return render(request, 'portfolio/home.html', {
        'message': 'Desconectado'
    })


def aboutme_page_view(request):
    context = {
        'cadeiras': Cadeira.objects.all(),
    }

    return render(request, 'portfolio/aboutme.html', context)


def projects_page_view(request):
    context = {
        'projetos': Projeto.objects.all(),
        'tfcs': TFC.objects.all()
    }

    return render(request, 'portfolio/projects.html', context)


def blog_page_view(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))

    context = {
        'posts': Post.objects.all(),
        'form': form
    }
    return render(request, 'portfolio/blog.html', context)


def quizz_page_view(request):
    if request.method == 'POST':
        n = request.POST['nome']
        p = pontuacao_quizz(request)
        r = PontuacaoQuizz(nome=n, pontuacao=p)
        r.save()

    context = {'data': desenha_grafico_resultados()}
    return render(request, 'portfolio/quizz.html', context)


def pontuacao_quizz(request):
    pontuacao = 0

    if request.POST['language'] == 'python':
        pontuacao += 1

    if request.POST.get('html') == 'hypertext':
        pontuacao += 1

    if request.POST['doctype'] == 'false':
        pontuacao += 1

    if request.POST['output1'] == 'maJ':
        pontuacao += 1

    if request.POST['init'] == 'package':
        pontuacao += 1

    if request.POST.get('format') == 'pixels':
        pontuacao += 1

    if request.POST['defined'] == 'false2':
        pontuacao += 1

    if request.POST['output2'] == '10, 11, 12, 13, 14, ':
        pontuacao += 1

    return pontuacao


def desenha_grafico_resultados():
    pontuacoes = PontuacaoQuizz.objects.all().order_by('pontuacao')

    nameslist = [pontuacao.nome for pontuacao in pontuacoes]
    scorelist = [pontuacao.pontuacao for pontuacao in pontuacoes]

    plt.barh(nameslist, scorelist)
    plt.ylabel("Score")
    plt.autoscale()

    fig = plt.gcf()
    plt.close()

    buf = io.BytesIO()
    fig.savefig(buf, format='png')

    buf.seek(0)
    string = base64.b64encode(buf.read())
    uri = urllib.parse.quote(string)

    return uri


def contact_page_view(request):
    return render(request, 'portfolio/contact.html')


@login_required
def novacadeira_page_view(request):
    form = CadeiraForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:aboutme'))

    context = {'form': form}

    return render(request, 'portfolio/novacadeira.html', context)


@login_required
def novoprojeto_page_view(request):
    form = ProjetoForm(request.POST, request.FILES or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:projects'))

    context = {'form': form}

    return render(request, 'portfolio/novoprojeto.html', context)


@login_required
def novotfc_page_view(request):
    form = TFCForm(request.POST, request.FILES or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:projects'))

    context = {'form': form}

    return render(request, 'portfolio/novotfc.html', context)


def web_page_view(request):
    context = {
        'tecnologias': Tecnologia.objects.all()
    }
    return render(request, 'portfolio/web.html', context)

portfolio/templates/portfolio/aboutme.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Me</title>

</head>
<body>
    {% extends 'portfolio/layout.html' %}

    {% block main %}
        {% load static %}

        <div class = "introdegree">
            <h1>About me</h1>
            <p>Currently I'm studying Computer Science and Engineering at Lusófona.</p>

            <div class = "video">
                <figure>
                    <iframe
                        src="https://www.youtube.com/embed/58U9ww280_M"
                        title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen>
                    </iframe>
                </figure>
            </div>
            <br>
            <h2>Degree</h2>
            <p>You can check out the subjects that I had on my degree with great detail.</p>
            <br>

            {% if request.user.is_authenticated %}
                <a class = "botaonovo" href="{% url 'portfolio:novacadeira' %}">Add new class</a>
            {% endif %}

        </div>

        <div class = "cadeiras">

            {% for cadeira in cadeiras %}
                <div >
                    <h3>{{ cadeira.nome }} - {{ cadeira.ano }}º year</h3>
                    <p>{{ cadeira.ranking }} stars</p>
                    <p>Ects: {{ cadeira.etcs }}</p>
                    <br>
                    <p>Topics:<br>{{ cadeira.topicos }}</p>
                    <br>
                    {% if cadeira.docente_teorica.linkLinkedin != null %}
                        <p>Teacher of theory:
                        <a href="{{ cadeira.docente_teorica.linkLinkedin }}">{{ cadeira.docente_teorica }}</a>
                        </p>
                    {% endif %}

                    <br>
                    {% if cadeira.docente_pratica.linkLinkedin != null %}
                        <p>Teacher of practices:
                        <a href="{{ cadeira.docente_pratica.linkLinkedin }}">{{ cadeira.docente_pratica }}</a>
                        </p>
                    {% endif %}

                    <br>
                </div>
            {% endfor %}

        </div>

        <div class = "introdegree">
            <h2>My education</h2>
            <p>This is where I graduated from high school and had the best experiences of my teenager life.</p>
        </div>

        <div class = "escolas">
            <div>
                <div>
                    <p><b>Nobel - Science and Technologys (2012-2020)</b><br>

                        <br><b>General formation:</b>

                        <br>English (17v)
                        <br>Philosophy (18v)
                        <br>Physical Education (15v)
                        <br>Portuguese (15v)<br>

                        <br><b>Specific:</b>

                        <br>Descriptive Geometry A (20v - Final exam: 18.7v)
                        <br>Mathematics A (17v - Final exam: 19.5v)
                    </p>
                </div>
                <div><img src="{% static 'portfolio/images/cs-logotipo_nobel.jpg' %}" alt=""></div>
            </div>
        </div>

        <div class = "introdegree">
            <h2>Certificates</h2>
            <p>Let's go through some of my achivements!</p>
            <br>
        </div>

        <div class = "certificados">
            <div>

                <div class = "introdegree">
                    <h3>Science Fair of Nobel</h3>
                    <p>I participated for 3 consecutive years on the Science Fair from my school.
                        <br>I had the opportunity to present fascinating curiositys in an interactive way and with a scientific explanation
                        (both in english and portuguese) in front of every class from the school.
                    </p>
                    <br>
                </div>
                <div class = "slider">
                    <div class = "images1">
                        <input type = "radio" name="slide1" id="img1" checked>
                        <input type = "radio" name="slide1" id="img2">
                        <input type = "radio" name="slide1" id="img3">
                        <img src="{% static 'portfolio/images/feira10.png' %}" class = "m1" alt="img1">
                        <img src="{% static 'portfolio/images/feira11.png' %}" class = "m2" alt="img2">
                        <img src="{% static 'portfolio/images/feira12.png' %}" class = "m3" alt="img3">
                    </div>
                    <div class = "dots1">
                        <label for = "img1" ></label>
                        <label for = "img2" ></label>
                        <label for = "img3" ></label>
                    </div>
                </div>

                <br>

                <div class = "introdegree">
                    <h3>Honor student</h3>
                    <p>Throughout my high school years, I've achieved one of my biggest accomplishments.<br>
                        On my 11th year I was nominated the Student of Merit of my class, because of my excellents results of that year.<br>
                        Also, I participated in the Helping Hand program, in which I showed a great commitment as a mentor to younger pupils.<br>
                        On 2020, I'm proud to say that I was an Honor level Student from Nobel, with a final average above 17.
                    </p>
                    <br>
                </div>

                <div class = "slider">
                    <div class = "images2">
                        <input type = "radio" name="slide2" id="img4" checked>
                        <input type = "radio" name="slide2" id="img5">
                        <input type = "radio" name="slide2" id="img6">
                        <img src="{% static 'portfolio/images/merito.png' %}" class = "m4" alt="img4">
                        <img src="{% static 'portfolio/images/helpinghand.png' %}" class = "m5" alt="img5">
                        <img src="{% static 'portfolio/images/honra.png' %}" class = "m6" alt="img6">
                    </div>
                    <div class = "dots2">
                        <label for = "img4" ></label>
                        <label for = "img5" ></label>
                        <label for = "img6" ></label>
                    </div>
                </div>

                <br>

                <div class = "introdegree">
                    <h3>Music lover</h3>
                    <p>These are some certificates that I own, which remind me of some events that I loved to be part of.</p>
                    <br>
                </div>

                <div class="slider2">
                    <div class="images3">
                        <img src="{% static 'portfolio/images/danca.png' %}" class = "m7" alt="img7">
                        <img src="{% static 'portfolio/images/piano.png' %}" class = "m8" alt="img8">
                    </div>
                </div>

                <br>

            </div>
        </div>

        <div class = "introdegree">
            <h2>Volunteering</h2>
            <br>
        </div>

        <div class = "voluntariado">
            <div>
                <div><img src="{% static 'portfolio/images/int-logotipo2 lusofona.png' %}" alt=""></div>
                <div id = "textvoluntariado">
                    <p><br>I manage all the social networks at the Department of Computer Engineering and Information Systems at Universidade Lusófona.
                        Including Tiktok, Instagram and Youtube.
                    <br><br>I created the logo of our Department, and I edited this video using Adobe Premiere Pro.
                    <br><br>I assure the social networks stay active, and I'm always creating new content every week.</p>
                </div>
                <div>
                    <figure>
                        <iframe src="https://www.youtube.com/embed/fFEQvthQR6Y"
                                title="YouTube video player" frameborder="0"
                                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                allowfullscreen>
                        </iframe>
                    </figure>
                </div>
            </div>
        </div>

        <div class = "introdegree">
            <h2>Hobbies</h2>
            <p>I love music! Singing, dancing and playing instruments was always a part of my life.</p>
            <br>
        </div>

        <div class = "hobbies">
            <div>
                <img src="{% static 'portfolio/images/int-logotipo festadamusica.png' %}" alt="">
                <p>I've been to a few music institutions, this was the last one that I've been to (2017-2020) and the one that I liked the most.
                <br>I learned to play the flute, the guitar and the piano. However, I felt more connected to the piano, and I've been playing it since I was a little girl.
                <br>I'm self-taught too, when I feel like I want to learn something new, I do it without a doubt!
                <br> <b>(2008-Now)</b> </p>
            </div>

            <div>
                <img src="{% static 'portfolio/images/int-logotipo karens.png' %}" alt="">
                <p>I love dancing. I met great people in this academy, and I had the most gratifying experiences of my entire life.
                <br>I had the pleasure of learning three dance genres: tap, hip hop and jazz.
                <br>I developed leadership skills to further improve my dance group's performance.
                <br> <b>(2015-2020)</b></p>
            </div>
        </div>


    {% endblock main %}

</body>
</html>

portfolio/templates/portfolio/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
</head>
<body>

    {% extends 'portfolio/layout.html' %}

    {% block main %}
        <div class = "introblog">
            <h1>Blog</h1>
        </div>

        <div class = "listaposts">

            {% for post in posts %}
                <div>
                    <h3>{{ post.titulo }}</h3>
                    <p>{{ post.descricao }}
                    <br>
                    <br>
                    {% if post.link != null or post.link != "" %}
                        <a class = "botaomore" href="{{ post.link }}">More</a>
                    {% endif %}</p>
                    <br>
                    Post by {{ post.autor }} on {{ post.criado }}
                    <br>
                </div>
            {% endfor %}

        </div>

        <div class = "novopost">
            <form action="" method="POST">

            <h2>New post</h2>
            {% csrf_token %}
            {{ form.as_p }}

            <input type="submit" value="Publicar" class="botaosubmeter">
            </form>
        </div>

    {% endblock main %}

</body>
</html>

portfolio/templates/portfolio/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact</title>
</head>
<body>

    {% extends 'portfolio/layout.html' %}

    {% block main %}
        {% load static %}

        <div class = "introcontact">
            <h1>Contact Me</h1>
            <p>Don't hesitate to contact me!</p>
        </div>

        <div class = "socials">
            <a href="https://www.instagram.com/sranene/">
                <img src="{% static 'portfolio/images/instagram.png' %}" target = "_blank" alt="">
            </a>
            <a href="https://github.com/Ines-a22001936">
                <img src="{% static 'portfolio/images/github.png' %}" target = "_blank" alt="">
            </a>
            <a href="https://www.linkedin.com/in/in%C3%AAs-marques-87249a209/">
                <img src="{% static 'portfolio/images/linkedin.png' %}" target = "_blank" alt="">
            </a>
        </div>
    {% endblock main %}

</body>
</html>

portfolio/templates/portfolio/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <title>Inês</title>

    {% load static %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'portfolio/css/layoutstyle.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/blogstyle.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/quizzstyle.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/homestyle.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/aboutmestyle.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/projectsstyle.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/contactstyle.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/novacadeirastyle.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/loginstyle.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/webstyle.css' %}">

    <script rel="stylesheet" src="{% static 'portfolio/js/tempo.js' %}"></script>

</head>
<body onload="time()">

    <header>
        <div>Inês Marques</div>

        <nav>
            <a href="{% url 'portfolio:home' %}">Home</a>
            <a href="{% url 'portfolio:aboutme' %}">About Me</a>
            <a href="{% url 'portfolio:projects' %}">Projects</a>
            <a href="{% url 'portfolio:blog' %}">Blog</a>
            <a href="{% url 'portfolio:web' %}">Web</a>
            <a href="{% url 'portfolio:contact' %}">Contact</a>
            {% if not request.user.is_authenticated %}
                <a href="{% url 'portfolio:login' %}">Login</a>
            {% else %}
                <a href="{% url 'portfolio:logout' %}">Logout</a>
            {% endif %}
        </nav>
    </header>

    <main>

        {% block main %}
        {% endblock main %}
        <div id = "currentTime"></div>
    </main>

    <footer>
        <div>ULHT 2022</div>
    </footer>

</body>
</html>

portfolio/templates/portfolio/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>

    {% extends 'portfolio/layout.html' %}


    {% block main %}

        <h1>Login</h1>

        {% if message %}
          <p> {{ message }} </p>
        {% endif %}

        <form action="" method="post">
            {% csrf_token %}
            <label>
                User: <input type="text" name="username" placeholder="username">
            </label>
            <label>
                Password: <input type="password" name="password" placeholder="password">
            </label>
            <label>
                <input class = "botaologin" type="submit" value="Login">
            </label>
        </form>

        <a class = "botaovoltar" href="{% url 'portfolio:home' %}">Go back Home</a>


    {% endblock main %}


</body>
</html>

portfolio/templates/portfolio/projects.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Projects</title>

</head>
<body>

    {% extends 'portfolio/layout.html' %}

    {% block main %}
        {% load static %}

        <div class = "introprojects">
            <h1>Projects</h1>
            <h2>My Projects</h2>
            <p>Here you will be able to see what projects I've done so far.</p>
            <br>
            {% if request.user.is_authenticated %}
                <a class = "botaonovo" href="{% url 'portfolio:novoprojeto' %}">Add new project</a>
            {% endif %}
        </div>


        <section>
            <div class = "projetos" id = "projetos">

                {% for projeto in projetos %}
                    <div>
                        <div><img src="{{ projeto.imagem.url }}" alt=""></div>
                        <div><p><b>{{ projeto.nome }}</b><br>
                            {{ projeto.descricao }}</p></div>
                    </div>
                {% endfor %}


                <div>
                    <div><img src="{% static 'portfolio/images/labs.png'%}" alt = ""></div>
                    <div><p><b>Web Development Labs</b><br>
                        You can check out this project by yourself.<br>
                        <a href="https://pw-labs-inesmarques-a22001936.herokuapp.com/">Click on this link!</a>
                    </p></div>
                </div>

            </div>

        </section>


        <div class = "introprojects">
            <h2>Best Final Year Project's from my University</h2>
            <p>These are some of the best Final Year Projects that I have seen and would like to share with you.</p>
            <br>
            {% if request.user.is_authenticated %}
                <a class = "botaonovo" href="{% url 'portfolio:novotfc' %}">Add new tfc</a>
            {% endif %}
        </div>


        <section>

            <div class = "tfcs" id = "tfcs">

                {% for tfc in tfcs %}
                <div >
                    <h2>{{ tfc.titulo }} - {{ tfc.ano }}</h2>
                    <p>Autors: {{ tfc.autor1 }} and {{ tfc.autor2 }}</p>
                    <p>Mentor: {{ tfc.orientador }}</p>
                    <br>
                    <p>{{ tfc.resumo }}</p>
                    <br>

                    <br>
                    <div>
                        <a href="{{ tfc.link }}">
                            <img src="{{ tfc.imagem.url }}" alt="">
                        </a>
                    </div>

                    <br>
                </div>
            {% endfor %}

            </div>

        </section>

    {% endblock main %}

</body>
</html>

portfolio/templates/portfolio/web.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Web</title>
</head>
<body>

    {% extends 'portfolio/layout.html' %}

    {% block main %}
        {% load static %}

        <div class = "introweb">
            <h1>Web Development</h1>
            <h2>Technologies</h2>
        </div>

        <div class = "tecnologias">

            {% for tecnologia in tecnologias %}
                <div>
                    <div>
                        <a href="{{ tecnologia.link }}">
                            <img src="{{ tecnologia.imagem.url }}" alt="">
                        </a>
                    </div>
                    <div>
                        <p><b>{{ tecnologia.nome }}</b>
                        <br>{{ tecnologia.descricao }}
                        <br>
                            <b>Developer: {{ tecnologia.criador }}</b>
                            <br>
                            Release date: {{ tecnologia.dataLancamento }}</p>
                    </div>
                </div>
            {% endfor %}

        </div>

        <div class = "introweb">
            <h2>About this website</h2>
            <h3>Entity Relationship Diagram (ERD)</h3>

            <img src="{% static 'portfolio/images/DER.png' %}" alt="">

            <h3>Structure</h3>

            <ul class = "estrutura">
                <li>Home (Hero page)</li>
                <li>About Me
                    <ul>
                        <li>Degree</li>
                        <li>My education</li>
                        <li>Certificates</li>
                        <li>Volunteering</li>
                        <li>Hobbies</li>
                    </ul>
                </li>
                <li>Projects
                    <ul>
                        <li>My Projects</li>
                        <li>Best Final Year Project's from my University</li>
                    </ul>
                </li>
                <li>Blog</li>
                <li>Web
                    <ul>
                        <li>Technologies</li>
                        <li>About this website</li>
                        <li>Quizz</li>
                    </ul>
                </li>
                <li>Contact</li>
                <li>Login</li>
            </ul>

            <h3>Technologies used in the creation of this website</h3>
        </div>

        <div class = "tecnologiasusadas">

            {% for tecnologia in tecnologias %}
                {% if tecnologia.nome == "Python" or tecnologia.nome == "HTML: HyperText Markup Language" or tecnologia.nome == "CSS: Cascade Style Sheet" or tecnologia.nome == "Django" or tecnologia.nome == "JavaScript"%}
                    <div>
                        <div>
                            <a href="{{ tecnologia.link }}">
                                <img src="{{ tecnologia.imagem.url }}" alt="">
                            </a>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}

        </div>

        <div class = "introweb">
            <h2>Do you want to test your skills?</h2>
            <br>
            <br>
            <br>
            <br>
            <br>
            <div>
                <a class = "botaoentrarquizz" href="{% url 'portfolio:quizz' %}">Take this quizz!!</a>
            </div>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>

        </div>



    {% endblock main %}

</body>
</html>